#!/bin/bash
# searches tests directory for .jack files and generates tests for them
# it assumes tests are in the directory containing this script
# it assumes that the executables are in the parent's lib directory

### DIRECTORY PATHNAMES ###

# nullglob is set so nothing runs if there are no test files
shopt -s nullglob

# work out relative path to tests directory
THISPWD=`pwd`

# find the test directory name
TESTDIR=`dirname $0`
cd "$TESTDIR"
TESTPWD=`pwd`

# find the parent directory name
PARENTDIR=`dirname "${TESTPWD}"`

# fix up pathnames to be displayed
if [ "$THISPWD" == "$TESTPWD" ] ; then
	TESTDIR=""
	PARENTDIR="../"
elif [ "$THISPWD" == "$PARENTDIR" ] ; then
	TESTDIR=`basename "$TESTPWD"`/
	PARENTDIR="./"
else
	echo "cd ${TESTDIR}"
	TESTDIR=`basename "$TESTPWD"`/
	PARENTDIR="./"
fi

### PRETTY STUFF ###

# if using an xterm - use headings and colour coded test results
if [ "${TERM:0:5}" == "xterm" -o "${TERM:0:2}" == "vt" ] ; then
	colorboldblack="\e[1;7;30m"
	colorboldgreen="\e[1;7;32m"
	colorboldred="\e[1;7;31m"
	undocolor="\e[0m"
else
	colorboldblack=
	colorboldgreen=
	colorboldred=
	undocolor=
fi

echo -e "${colorboldblack}                         | parser? | pretty? | codegen? | opt-r? ${undocolor}"
# search for .jack files and see if they have test output yet
for i in */*.jack ; do
	printf -v source_file "%-24s" "${i}"

	# attempt to parse the .jack file
	cat ${i} | ../lib/wparser > xtemp 2> /dev/null
	rm -f "${i}.parser."*

	# if output was empty there must only be one test output file .jack.parser.empty
	if [ ! -s xtemp ] ; then
		touch "${i}.parser.empty"
         	echo "${source_file} |   DNC   |   No    |    No    |   No"
	else
		cat xtemp | ../lib/pxml > "${i}.parser.pxml.Pxml"
		cat xtemp | ../lib/wpretty > "${i}.parser.pretty.Pjack"
		cat xtemp | ../lib/wcodegen > "${i}.parser.codegen.Cvm"
		cat xtemp | ../lib/wopt-r | ../lib/pxml > "${i}.parser.opt-r.pxml.Pxml"
         	echo "${source_file} |   Yes   |   Yes   |    Yes   |   Yes"
	fi
	rm -f xtemp
done
echo

